# Generated by Django 6.1 on 2026-08-22 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.JSONField(default=list, help_text='List of specializations')),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('certifications', models.JSONField(default=list, help_text='List of certifications')),
                ('bio', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('availability', models.CharField(blank=True, help_text='e.g. Mon–Sat, 6AM–8PM', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainers',
            },
        ),
        migrations.CreateModel(
            name='TrainerMonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='1=January, 12=December')),
                ('year', models.PositiveSmallIntegerField()),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overachievement', models.PositiveIntegerField(default=0)),
                ('is_overridden', models.BooleanField(default=False)),
                ('original_target', models.PositiveIntegerField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_overrides', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_performances', to='trainers.trainer')),
            ],
            options={
                'db_table': 'trainer_monthly_performance',
                'ordering': ['-year', '-month'],
                'unique_together': {('trainer', 'month', 'year')},
            },
        ),
    ]
