# Generated by Django 6.0.5 on 2026-09-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('chest_cm', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('arms_cm', models.FloatField(blank=True, null=True)),
                ('legs_cm', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='members.member')),
            ],
            options={
                'db_table': 'body_measurements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MemberAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='Emoji or icon name', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='members.member')),
            ],
            options={
                'db_table': 'member_achievements',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general_fitness', 'General Fitness'), ('custom', 'Custom')], default='general_fitness', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('current_value', models.FloatField(default=0.0)),
                ('target_value', models.FloatField()),
                ('unit', models.CharField(help_text='e.g. kg, lbs, km, %', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='members.member')),
            ],
            options={
                'db_table': 'member_goals',
                'ordering': ['is_achieved', 'deadline'],
            },
        ),
    ]
