# Generated by Django 6.1 on 2026-08-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_inr', models.PositiveIntegerField(help_text='Amount in Indian Rupees (paise-less)')),
                ('method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('net_banking', 'Net Banking'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255)),
                ('upi_ref', models.CharField(blank=True, help_text='UPI Reference number', max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='memberships.membership')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['member', 'status'], name='payments_member__58330e_idx'), models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx')],
            },
        ),
    ]
